jQuery(document).ready(function () {
jQuery("#photo-gallery").nanogallery2( {
    // ### gallery settings ### 
    // TODO: Set gallery theme with dark mode toggle
    thumbnailL1Height:  300,
    thumbnailL1Width:   'auto',
    thumbnailHeight:  600,
    thumbnailWidth:   'auto',
    thumbnailGutterHeight: 5,
    thumbnailGutterWidth: 5,
    thumbnailBorderHorizontal: 0,
    thumbnailBorderVertical: 0,
    thumbnailLabel:     { display: false },
    itemsBaseURL:     'https://liambsullivan.com/portfolio/',
    
    // ### generate gallery content ### 
    items: [
        { srct: 'thumbnails/ElleLevi2.jpg', title: 'Elle Levi',  ID: 1000,	kind:'album' },
        { src: 'ElleLevi1.jpg', srct: 'thumbnails/ElleLevi1.jpg', ID: 1, albumID: 1000 }, //! Setting ID to 0 results in UI bug on hover
        { src: 'ElleLevi2.jpg', srct: 'thumbnails/ElleLevi2.jpg', ID: 2, albumID: 1000 },
        { src: 'ElleLevi3.jpg', srct: 'thumbnails/ElleLevi3.jpg', ID: 3, albumID: 1000 },
        { src: 'ElleLevi4.jpg', srct: 'thumbnails/ElleLevi4.jpg', ID: 4, albumID: 1000 },
        { src: 'ElleLevi5.jpg', srct: 'thumbnails/ElleLevi5.jpg', ID: 5, albumID: 1000 },

        { srct: 'thumbnails/PaigeSharkCherryBlossoms-11.jpg', title: 'Paige Shark - Cherry Blossoms',  ID: 1001,	kind:'album' },
        { src: 'PaigeSharkCherryBlossoms-1.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-1.jpg', ID: 20, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-2.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-2.jpg', ID: 21, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-3.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-3.jpg', ID: 22, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-4.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-4.jpg', ID: 23, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-5.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-5.jpg', ID: 24, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-6.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-6.jpg', ID: 25, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-7.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-7.jpg', ID: 26, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-8.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-8.jpg', ID: 27, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-9.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-9.jpg', ID: 28, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-10.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-10.jpg', ID: 29, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-11.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-11.jpg', ID: 30, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-12.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-12.jpg', ID: 31, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-13.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-13.jpg', ID: 32, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-14.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-14.jpg', ID: 33, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-15.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-15.jpg', ID: 34, albumID: 1001 },
        { src: 'PaigeSharkCherryBlossoms-16.jpg', srct: 'thumbnails/PaigeSharkCherryBlossoms-16.jpg', ID: 35, albumID: 1001 },
        
        { srct: 'thumbnails/KaiWatkins-11.jpg', title: 'Kai Watkins - Gels',  ID: 1002,	kind:'album' },
        { src: 'KaiWatkins-1.jpg', srct: 'thumbnails/KaiWatkins-1.jpg', ID: 40, albumID: 1002 },
        { src: 'KaiWatkins-2.jpg', srct: 'thumbnails/KaiWatkins-2.jpg', ID: 41, albumID: 1002 },
        { src: 'KaiWatkins-3.jpg', srct: 'thumbnails/KaiWatkins-3.jpg', ID: 42, albumID: 1002 },
        { src: 'KaiWatkins-4.jpg', srct: 'thumbnails/KaiWatkins-4.jpg', ID: 43, albumID: 1002 },
        { src: 'KaiWatkins-5.jpg', srct: 'thumbnails/KaiWatkins-5.jpg', ID: 44, albumID: 1002 },
        { src: 'KaiWatkins-6.jpg', srct: 'thumbnails/KaiWatkins-6.jpg', ID: 45, albumID: 1002 },
        { src: 'KaiWatkins-7.jpg', srct: 'thumbnails/KaiWatkins-7.jpg', ID: 46, albumID: 1002 },
        { src: 'KaiWatkins-8.jpg', srct: 'thumbnails/KaiWatkins-8.jpg', ID: 47, albumID: 1002 },
        { src: 'KaiWatkins-9.jpg', srct: 'thumbnails/KaiWatkins-9.jpg', ID: 48, albumID: 1002 },
        { src: 'KaiWatkins-10.jpg', srct: 'thumbnails/KaiWatkins-10.jpg', ID: 49, albumID: 1002 },
        { src: 'KaiWatkins-11.jpg', srct: 'thumbnails/KaiWatkins-11.jpg', ID: 50, albumID: 1002 },
        { src: 'KaiWatkins-12.jpg', srct: 'thumbnails/KaiWatkins-12.jpg', ID: 51, albumID: 1002 },
        { src: 'KaiWatkins-13.jpg', srct: 'thumbnails/KaiWatkins-13.jpg', ID: 52, albumID: 1002 },
        { src: 'KaiWatkins-14.jpg', srct: 'thumbnails/KaiWatkins-14.jpg', ID: 53, albumID: 1002 },
        { src: 'KaiWatkins-15.jpg', srct: 'thumbnails/KaiWatkins-15.jpg', ID: 54, albumID: 1002 },
        { src: 'KaiWatkins-16.jpg', srct: 'thumbnails/KaiWatkins-16.jpg', ID: 55, albumID: 1002 },
        { src: 'KaiWatkins-17.jpg', srct: 'thumbnails/KaiWatkins-17.jpg', ID: 56, albumID: 1002 },

        { srct: 'thumbnails/PaigeShark-12.jpg', title: 'Paige Shark - Studio',  ID: 1003,	kind:'album' },
        { src: 'PaigeShark-1.jpg', srct: 'thumbnails/PaigeShark-1.jpg', ID: 60, albumID: 1003 },
        { src: 'PaigeShark-2.jpg', srct: 'thumbnails/PaigeShark-2.jpg', ID: 61, albumID: 1003 },
        { src: 'PaigeShark-3.jpg', srct: 'thumbnails/PaigeShark-3.jpg', ID: 62, albumID: 1003 },
        { src: 'PaigeShark-4.jpg', srct: 'thumbnails/PaigeShark-4.jpg', ID: 63, albumID: 1003 },
        { src: 'PaigeShark-5.jpg', srct: 'thumbnails/PaigeShark-5.jpg', ID: 64, albumID: 1003 },
        { src: 'PaigeShark-6.jpg', srct: 'thumbnails/PaigeShark-6.jpg', ID: 65, albumID: 1003 },
        { src: 'PaigeShark-7.jpg', srct: 'thumbnails/PaigeShark-7.jpg', ID: 66, albumID: 1003 },
        { src: 'PaigeShark-8.jpg', srct: 'thumbnails/PaigeShark-8.jpg', ID: 67, albumID: 1003 },
        { src: 'PaigeShark-9.jpg', srct: 'thumbnails/PaigeShark-9.jpg', ID: 68, albumID: 1003 },
        { src: 'PaigeShark-10.jpg', srct: 'thumbnails/PaigeShark-10.jpg', ID: 69, albumID: 1003 },
        { src: 'PaigeShark-11.jpg', srct: 'thumbnails/PaigeShark-11.jpg', ID: 70, albumID: 1003 },
        { src: 'PaigeShark-12.jpg', srct: 'thumbnails/PaigeShark-12.jpg', ID: 71, albumID: 1003 },
        { src: 'PaigeShark-13.jpg', srct: 'thumbnails/PaigeShark-13.jpg', ID: 72, albumID: 1003 },

        { srct: 'thumbnails/Kai-5.jpg', title: 'Kai Watkins - Studio',  ID: 1004,	kind:'album' },
        { src: 'Kai-1.jpg', srct: 'thumbnails/Kai-1.jpg', ID: 80, albumID: 1004 },
        { src: 'Kai-2.jpg', srct: 'thumbnails/Kai-2.jpg', ID: 81, albumID: 1004 },
        { src: 'Kai-3.jpg', srct: 'thumbnails/Kai-3.jpg', ID: 82, albumID: 1004 },
        { src: 'Kai-4.jpg', srct: 'thumbnails/Kai-4.jpg', ID: 83, albumID: 1004 },
        { src: 'Kai-5.jpg', srct: 'thumbnails/Kai-5.jpg', ID: 84, albumID: 1004 },
        { src: 'Kai-6.jpg', srct: 'thumbnails/Kai-6.jpg', ID: 85, albumID: 1004 },
        { src: 'Kai-7.jpg', srct: 'thumbnails/Kai-7.jpg', ID: 86, albumID: 1004 },
        { src: 'Kai-8.jpg', srct: 'thumbnails/Kai-8.jpg', ID: 87, albumID: 1004 },
        { src: 'Kai-9.jpg', srct: 'thumbnails/Kai-9.jpg', ID: 88, albumID: 1004 },
        { src: 'Kai-10.jpg', srct: 'thumbnails/Kai-10.jpg', ID: 89, albumID: 1004 },
        
        { srct: 'thumbnails/ErinHopewellSeniorPorts-7.jpg', title: 'Erin Hopewell - Senior Portraits',  ID: 1005,	kind:'album' },
        { src: 'ErinHopewellSeniorPorts-1.jpg', srct: 'thumbnails/ErinHopewellSeniorPorts-1.jpg', ID: 100, albumID: 1005 },
        { src: 'ErinHopewellSeniorPorts-2.jpg', srct: 'thumbnails/ErinHopewellSeniorPorts-2.jpg', ID: 101, albumID: 1005 },
        { src: 'ErinHopewellSeniorPorts-3.jpg', srct: 'thumbnails/ErinHopewellSeniorPorts-3.jpg', ID: 102, albumID: 1005 },
        { src: 'ErinHopewellSeniorPorts-4.jpg', srct: 'thumbnails/ErinHopewellSeniorPorts-4.jpg', ID: 103, albumID: 1005 },
        { src: 'ErinHopewellSeniorPorts-5.jpg', srct: 'thumbnails/ErinHopewellSeniorPorts-5.jpg', ID: 104, albumID: 1005 },
        { src: 'ErinHopewellSeniorPorts-6.jpg', srct: 'thumbnails/ErinHopewellSeniorPorts-6.jpg', ID: 105, albumID: 1005 },
        { src: 'ErinHopewellSeniorPorts-7.jpg', srct: 'thumbnails/ErinHopewellSeniorPorts-7.jpg', ID: 106, albumID: 1005 },
        { src: 'ErinHopewellSeniorPorts-8.jpg', srct: 'thumbnails/ErinHopewellSeniorPorts-8.jpg', ID: 107, albumID: 1005 },

        { srct: 'thumbnails/TheCats1.jpg', title: 'The Cats',  ID: 1006,	kind:'album' },
        { src: 'TheCats1.jpg', srct: 'thumbnails/TheCats1.jpg', ID: 120, albumID: 1006 },
        { src: 'TheCats2.jpg', srct: 'thumbnails/TheCats2.jpg', ID: 121, albumID: 1006 },

        { srct: 'thumbnails/YuliyaDadeyava4.jpg', title: 'Yuliya Dadayeva',  ID: 1007,	kind:'album' },
        { src: 'YuliyaDadeyava1.jpg', srct: 'thumbnails/YuliyaDadeyava1.jpg', ID: 140, albumID: 1007 },
        { src: 'YuliyaDadeyava2.jpg', srct: 'thumbnails/YuliyaDadeyava2.jpg', ID: 141, albumID: 1007 },
        { src: 'YuliyaDadeyava3.jpg', srct: 'thumbnails/YuliyaDadeyava3.jpg', ID: 142, albumID: 1007 },
        { src: 'YuliyaDadeyava4.jpg', srct: 'thumbnails/YuliyaDadeyava4.jpg', ID: 143, albumID: 1007 },

        { srct: 'thumbnails/SamanthaKay-5.jpg', title: 'Samantha Kay',  ID: 1008,	kind:'album' },
        { src: 'SamanthaKay-1.jpg', srct: 'thumbnails/SamanthaKay-1.jpg', ID: 160, albumID: 1008 },
        { src: 'SamanthaKay-2.jpg', srct: 'thumbnails/SamanthaKay-2.jpg', ID: 161, albumID: 1008 },
        { src: 'SamanthaKay-3.jpg', srct: 'thumbnails/SamanthaKay-3.jpg', ID: 162, albumID: 1008 },
        { src: 'SamanthaKay-4.jpg', srct: 'thumbnails/SamanthaKay-4.jpg', ID: 163, albumID: 1008 },
        { src: 'SamanthaKay-5.jpg', srct: 'thumbnails/SamanthaKay-5.jpg', ID: 164, albumID: 1008 },
        { src: 'SamanthaKay-6.jpg', srct: 'thumbnails/SamanthaKay-6.jpg', ID: 165, albumID: 1008 },
        { src: 'SamanthaKay-7.jpg', srct: 'thumbnails/SamanthaKay-7.jpg', ID: 166, albumID: 1008 },

        { srct: 'thumbnails/ErinBlue-8.jpg', title: 'AP Studio Art - Blue',  ID: 1009,	kind:'album' },
        { src: 'ErinBlue-1.jpg', srct: 'thumbnails/ErinBlue-1.jpg', ID: 180, albumID: 1009 },
        { src: 'ErinBlue-2.jpg', srct: 'thumbnails/ErinBlue-2.jpg', ID: 181, albumID: 1009 },
        { src: 'ErinBlue-3.jpg', srct: 'thumbnails/ErinBlue-3.jpg', ID: 182, albumID: 1009 },
        { src: 'ErinBlue-4.jpg', srct: 'thumbnails/ErinBlue-4.jpg', ID: 183, albumID: 1009 },
        { src: 'ErinBlue-5.jpg', srct: 'thumbnails/ErinBlue-5.jpg', ID: 184, albumID: 1009 },
        { src: 'ErinBlue-6.jpg', srct: 'thumbnails/ErinBlue-6.jpg', ID: 185, albumID: 1009 },
        { src: 'ErinBlue-7.jpg', srct: 'thumbnails/ErinBlue-7.jpg', ID: 186, albumID: 1009 },
        { src: 'ErinBlue-8.jpg', srct: 'thumbnails/ErinBlue-8.jpg', ID: 187, albumID: 1009 },
        { src: 'ErinBlue-9.jpg', srct: 'thumbnails/ErinBlue-9.jpg', ID: 188, albumID: 1009 },
        { src: 'ErinBlue-10.jpg', srct: 'thumbnails/ErinBlue-10.jpg', ID: 189, albumID: 1009 },

        { srct: 'thumbnails/CarolineJonesYellow-15.jpg', title: 'AP Studio Art - Yellow',  ID: 1011,	kind:'album' },
        { src: 'CarolineJonesYellow-1.jpg', srct: 'thumbnails/CarolineJonesYellow-1.jpg', ID: 220, albumID: 1011 },
        { src: 'CarolineJonesYellow-2.jpg', srct: 'thumbnails/CarolineJonesYellow-2.jpg', ID: 221, albumID: 1011 },
        { src: 'CarolineJonesYellow-3.jpg', srct: 'thumbnails/CarolineJonesYellow-3.jpg', ID: 222, albumID: 1011 },
        { src: 'CarolineJonesYellow-4.jpg', srct: 'thumbnails/CarolineJonesYellow-4.jpg', ID: 223, albumID: 1011 },
        { src: 'CarolineJonesYellow-5.jpg', srct: 'thumbnails/CarolineJonesYellow-5.jpg', ID: 224, albumID: 1011 },
        { src: 'CarolineJonesYellow-6.jpg', srct: 'thumbnails/CarolineJonesYellow-6.jpg', ID: 225, albumID: 1011 },
        { src: 'CarolineJonesYellow-7.jpg', srct: 'thumbnails/CarolineJonesYellow-7.jpg', ID: 226, albumID: 1011 },
        { src: 'CarolineJonesYellow-8.jpg', srct: 'thumbnails/CarolineJonesYellow-8.jpg', ID: 227, albumID: 1011 },
        { src: 'CarolineJonesYellow-9.jpg', srct: 'thumbnails/CarolineJonesYellow-9.jpg', ID: 228, albumID: 1011 },
        { src: 'CarolineJonesYellow-10.jpg', srct: 'thumbnails/CarolineJonesYellow-10.jpg', ID: 229, albumID: 1011 },
        { src: 'CarolineJonesYellow-11.jpg', srct: 'thumbnails/CarolineJonesYellow-11.jpg', ID: 230, albumID: 1011 },
        { src: 'CarolineJonesYellow-12.jpg', srct: 'thumbnails/CarolineJonesYellow-12.jpg', ID: 231, albumID: 1011 },
        { src: 'CarolineJonesYellow-13.jpg', srct: 'thumbnails/CarolineJonesYellow-13.jpg', ID: 232, albumID: 1011 },
        { src: 'CarolineJonesYellow-14.jpg', srct: 'thumbnails/CarolineJonesYellow-14.jpg', ID: 233, albumID: 1011 },
        { src: 'CarolineJonesYellow-15.jpg', srct: 'thumbnails/CarolineJonesYellow-15.jpg', ID: 234, albumID: 1011 },

        { srct: 'thumbnails/AvaAcostaPurple-14.jpg', title: 'AP Studio Art - Purple',  ID: 1012,	kind:'album' },
        { src: 'AvaAcostaPurple-1.jpg', srct: 'thumbnails/AvaAcostaPurple-1.jpg', ID: 240, albumID: 1012 },
        { src: 'AvaAcostaPurple-2.jpg', srct: 'thumbnails/AvaAcostaPurple-2.jpg', ID: 241, albumID: 1012 },
        { src: 'AvaAcostaPurple-3.jpg', srct: 'thumbnails/AvaAcostaPurple-3.jpg', ID: 242, albumID: 1012 },
        { src: 'AvaAcostaPurple-4.jpg', srct: 'thumbnails/AvaAcostaPurple-4.jpg', ID: 243, albumID: 1012 },
        { src: 'AvaAcostaPurple-5.jpg', srct: 'thumbnails/AvaAcostaPurple-5.jpg', ID: 244, albumID: 1012 },
        { src: 'AvaAcostaPurple-6.jpg', srct: 'thumbnails/AvaAcostaPurple-6.jpg', ID: 245, albumID: 1012 },
        { src: 'AvaAcostaPurple-7.jpg', srct: 'thumbnails/AvaAcostaPurple-7.jpg', ID: 246, albumID: 1012 },
        { src: 'AvaAcostaPurple-8.jpg', srct: 'thumbnails/AvaAcostaPurple-8.jpg', ID: 247, albumID: 1012 },
        { src: 'AvaAcostaPurple-9.jpg', srct: 'thumbnails/AvaAcostaPurple-9.jpg', ID: 248, albumID: 1012 },
        { src: 'AvaAcostaPurple-10.jpg', srct: 'thumbnails/AvaAcostaPurple-10.jpg', ID: 249, albumID: 1012 },
        { src: 'AvaAcostaPurple-11.jpg', srct: 'thumbnails/AvaAcostaPurple-11.jpg', ID: 250, albumID: 1012 },
        { src: 'AvaAcostaPurple-12.jpg', srct: 'thumbnails/AvaAcostaPurple-12.jpg', ID: 251, albumID: 1012 },
        { src: 'AvaAcostaPurple-13.jpg', srct: 'thumbnails/AvaAcostaPurple-13.jpg', ID: 252, albumID: 1012 },
        { src: 'AvaAcostaPurple-14.jpg', srct: 'thumbnails/AvaAcostaPurple-14.jpg', ID: 253, albumID: 1012 },
        { src: 'AvaAcostaPurple-15.jpg', srct: 'thumbnails/AvaAcostaPurple-15.jpg', ID: 254, albumID: 1012 },

        { srct: 'thumbnails/Sophie-2.jpg', title: 'Sophie',  ID: 1013,	kind:'album' },
        { src: 'Sophie-1.jpg', srct: 'thumbnails/Sophie-1.jpg', ID: 260, albumID: 1013 },
        { src: 'Sophie-2.jpg', srct: 'thumbnails/Sophie-2.jpg', ID: 261, albumID: 1013 },
        { src: 'Sophie-3.jpg', srct: 'thumbnails/Sophie-3.jpg', ID: 262, albumID: 1013 },
        { src: 'Sophie-4.jpg', srct: 'thumbnails/Sophie-4.jpg', ID: 263, albumID: 1013 },
        { src: 'Sophie-5.jpg', srct: 'thumbnails/Sophie-5.jpg', ID: 264, albumID: 1013 },
        { src: 'Sophie-6.jpg', srct: 'thumbnails/Sophie-6.jpg', ID: 265, albumID: 1013 },
        { src: 'Sophie-7.jpg', srct: 'thumbnails/Sophie-7.jpg', ID: 266, albumID: 1013 },
        { src: 'Sophie-8.jpg', srct: 'thumbnails/Sophie-8.jpg', ID: 267, albumID: 1013 },
        { src: 'Sophie-9.jpg', srct: 'thumbnails/Sophie-9.jpg', ID: 268, albumID: 1013 },
        { src: 'Sophie-10.jpg', srct: 'thumbnails/Sophie-10.jpg', ID: 269, albumID: 1013 },
        { src: 'Sophie-11.jpg', srct: 'thumbnails/Sophie-11.jpg', ID: 270, albumID: 1013 },
        { src: 'Sophie-12.jpg', srct: 'thumbnails/Sophie-12.jpg', ID: 271, albumID: 1013 },

        { srct: 'thumbnails/FunkyLamp5.jpg', title: 'Funky Lamp - Band',  ID: 1014,	kind:'album' },
        { src: 'FunkyLamp1.jpg', srct: 'thumbnails/FunkyLamp1.jpg', ID: 280, albumID: 1014 },
        { src: 'FunkyLamp2.jpg', srct: 'thumbnails/FunkyLamp2.jpg', ID: 281, albumID: 1014 },
        { src: 'FunkyLamp3.jpg', srct: 'thumbnails/FunkyLamp3.jpg', ID: 282, albumID: 1014 },
        { src: 'FunkyLamp4.jpg', srct: 'thumbnails/FunkyLamp4.jpg', ID: 283, albumID: 1014 },
        { src: 'FunkyLamp5.jpg', srct: 'thumbnails/FunkyLamp5.jpg', ID: 284, albumID: 1014 },
        { src: 'FunkyLamp6.jpg', srct: 'thumbnails/FunkyLamp6.jpg', ID: 285, albumID: 1014 },
        
        { srct: 'thumbnails/PitterPatter1.jpg', title: 'Pitter Patter - Band',  ID: 1015,	kind:'album' },
        { src: 'PitterPatter1.jpg', srct: 'thumbnails/PitterPatter1.jpg', ID: 300, albumID: 1015 },
        { src: 'PitterPatter2.jpg', srct: 'thumbnails/PitterPatter2.jpg', ID: 301, albumID: 1015 },

        { srct: 'thumbnails/AvaAcostaBurkeLake-9.jpg', title: 'Ava Acosta', ID: 1016,	kind:'album' },
        { src: 'AvaAcostaBurkeLake-1.jpg', srct: 'thumbnails/AvaAcostaBurkeLake-1.jpg', ID: 320, albumID: 1016 },
        { src: 'AvaAcostaBurkeLake-2.jpg', srct: 'thumbnails/AvaAcostaBurkeLake-2.jpg', ID: 321, albumID: 1016 },
        { src: 'AvaAcostaBurkeLake-3.jpg', srct: 'thumbnails/AvaAcostaBurkeLake-3.jpg', ID: 322, albumID: 1016 },
        { src: 'AvaAcostaBurkeLake-4.jpg', srct: 'thumbnails/AvaAcostaBurkeLake-4.jpg', ID: 323, albumID: 1016 },
        { src: 'AvaAcostaBurkeLake-5.jpg', srct: 'thumbnails/AvaAcostaBurkeLake-5.jpg', ID: 324, albumID: 1016 },
        { src: 'AvaAcostaBurkeLake-6.jpg', srct: 'thumbnails/AvaAcostaBurkeLake-6.jpg', ID: 325, albumID: 1016 },
        { src: 'AvaAcostaBurkeLake-7.jpg', srct: 'thumbnails/AvaAcostaBurkeLake-7.jpg', ID: 326, albumID: 1016 },
        { src: 'AvaAcostaBurkeLake-8.jpg', srct: 'thumbnails/AvaAcostaBurkeLake-8.jpg', ID: 327, albumID: 1016 },
        { src: 'AvaAcostaBurkeLake-9.jpg', srct: 'thumbnails/AvaAcostaBurkeLake-9.jpg', ID: 328, albumID: 1016 },
        { src: 'AvaAcostaBurkeLake-10.jpg', srct: 'thumbnails/AvaAcostaBurkeLake-10.jpg', ID: 329, albumID: 1016 },            

        { srct: 'thumbnails/SelfPortraits-5.jpg', title: 'Self Portraits', ID: 1017,	kind:'album' },
        { src: 'SelfPortraits-1.jpg', srct: 'thumbnails/SelfPortraits-1.jpg', ID: 340, albumID: 1017 },
        { src: 'SelfPortraits-2.jpg', srct: 'thumbnails/SelfPortraits-2.jpg', ID: 341, albumID: 1017 },
        { src: 'SelfPortraits-3.jpg', srct: 'thumbnails/SelfPortraits-3.jpg', ID: 342, albumID: 1017 },
        { src: 'SelfPortraits-4.jpg', srct: 'thumbnails/SelfPortraits-4.jpg', ID: 343, albumID: 1017 },
        { src: 'SelfPortraits-5.jpg', srct: 'thumbnails/SelfPortraits-5.jpg', ID: 344, albumID: 1017 },
        { src: 'SelfPortraits-6.jpg', srct: 'thumbnails/SelfPortraits-6.jpg', ID: 345, albumID: 1017 },
        { src: 'SelfPortraits-7.jpg', srct: 'thumbnails/SelfPortraits-7.jpg', ID: 346, albumID: 1017 },
        { src: 'SelfPortraits-8.jpg', srct: 'thumbnails/SelfPortraits-8.jpg', ID: 347, albumID: 1017 },
        { src: 'SelfPortraits-9.jpg', srct: 'thumbnails/SelfPortraits-9.jpg', ID: 348, albumID: 1017 },

        { srct: 'thumbnails/BevinSurbey5.jpg', title: 'Bevin Surbey', ID: 1018,	kind:'album' },
        { src: 'BevinSurbey1.jpg', srct: 'thumbnails/BevinSurbey1.jpg', ID: 360, albumID: 1018 },
        { src: 'BevinSurbey2.jpg', srct: 'thumbnails/BevinSurbey2.jpg', ID: 361, albumID: 1018 },
        { src: 'BevinSurbey3.jpg', srct: 'thumbnails/BevinSurbey3.jpg', ID: 362, albumID: 1018 },
        { src: 'BevinSurbey4.jpg', srct: 'thumbnails/BevinSurbey4.jpg', ID: 363, albumID: 1018 },
        { src: 'BevinSurbey5.jpg', srct: 'thumbnails/BevinSurbey5.jpg', ID: 364, albumID: 1018 },
      
        { srct: 'thumbnails/JackHopewell2.jpg', title: 'Jack Hopewell', ID: 1019,	kind:'album' },
        { src: 'JackHopewell1.jpg', srct: 'thumbnails/JackHopewell1.jpg', ID: 380, albumID: 1019 },
        { src: 'JackHopewell2.jpg', srct: 'thumbnails/JackHopewell2.jpg', ID: 381, albumID: 1019 },
        { src: 'JackHopewell3.jpg', srct: 'thumbnails/JackHopewell3.jpg', ID: 382, albumID: 1019 },
        { src: 'JackHopewell4.jpg', srct: 'thumbnails/JackHopewell4.jpg', ID: 383, albumID: 1019 },
        { src: 'JackHopewell5.jpg', srct: 'thumbnails/JackHopewell5.jpg', ID: 384, albumID: 1019 },

        { srct: 'thumbnails/YellowBridges3.jpg', title: 'Yellow Bridges - Band', ID: 1020,	kind:'album' },
        { src: 'YellowBridges1.jpg', srct: 'thumbnails/YellowBridges1.jpg', ID: 400, albumID: 1020 },
        { src: 'YellowBridges2.jpg', srct: 'thumbnails/YellowBridges2.jpg', ID: 401, albumID: 1020 },
        { src: 'YellowBridges3.jpg', srct: 'thumbnails/YellowBridges3.jpg', ID: 402, albumID: 1020 },
        { src: 'YellowBridges4.jpg', srct: 'thumbnails/YellowBridges4.jpg', ID: 403, albumID: 1020 },
        { src: 'YellowBridges5.jpg', srct: 'thumbnails/YellowBridges5.jpg', ID: 404, albumID: 1020 },
        { src: 'YellowBridges6.jpg', srct: 'thumbnails/YellowBridges6.jpg', ID: 405, albumID: 1020 },

        { srct: 'thumbnails/PG-6.jpg', title: 'Post Genre - Church Show 1', ID: 1021,	kind:'album' },
        { src: 'PG-1.jpg', srct: 'thumbnails/PG-1.jpg', ID: 420, albumID: 1021 },
        { src: 'PG-2.jpg', srct: 'thumbnails/PG-2.jpg', ID: 421, albumID: 1021 },
        { src: 'PG-3.jpg', srct: 'thumbnails/PG-3.jpg', ID: 422, albumID: 1021 },
        { src: 'PG-4.jpg', srct: 'thumbnails/PG-4.jpg', ID: 423, albumID: 1021 },
        { src: 'PG-5.jpg', srct: 'thumbnails/PG-5.jpg', ID: 424, albumID: 1021 },
        { src: 'PG-6.jpg', srct: 'thumbnails/PG-6.jpg', ID: 425, albumID: 1021 },
        { src: 'PG-7.jpg', srct: 'thumbnails/PG-7.jpg', ID: 426, albumID: 1021 },
        { src: 'PG-8.jpg', srct: 'thumbnails/PG-8.jpg', ID: 427, albumID: 1021 },
        { src: 'PG-9.jpg', srct: 'thumbnails/PG-9.jpg', ID: 428, albumID: 1021 },
        { src: 'PG-10.jpg', srct: 'thumbnails/PG-10.jpg', ID: 429, albumID: 1021 },
        { src: 'PG-11.jpg', srct: 'thumbnails/PG-11.jpg', ID: 430, albumID: 1021 },
        { src: 'PG-12.jpg', srct: 'thumbnails/PG-12.jpg', ID: 431, albumID: 1021 },
        { src: 'PG-13.jpg', srct: 'thumbnails/PG-13.jpg', ID: 432, albumID: 1021 },
        { src: 'PG-14.jpg', srct: 'thumbnails/PG-14.jpg', ID: 433, albumID: 1021 },
        { src: 'PG-15.jpg', srct: 'thumbnails/PG-15.jpg', ID: 434, albumID: 1021 },
        { src: 'PG-16.jpg', srct: 'thumbnails/PG-16.jpg', ID: 435, albumID: 1021 },
        { src: 'PG-17.jpg', srct: 'thumbnails/PG-17.jpg', ID: 436, albumID: 1021 },
        { src: 'PG-18.jpg', srct: 'thumbnails/PG-18.jpg', ID: 437, albumID: 1021 },
        { src: 'PG-19.jpg', srct: 'thumbnails/PG-19.jpg', ID: 438, albumID: 1021 },
        { src: 'PG-20.jpg', srct: 'thumbnails/PG-20.jpg', ID: 439, albumID: 1021 },
        { src: 'PG-21.jpg', srct: 'thumbnails/PG-21.jpg', ID: 440, albumID: 1021 },
        { src: 'PG-22.jpg', srct: 'thumbnails/PG-22.jpg', ID: 441, albumID: 1021 },
        { src: 'PG-23.jpg', srct: 'thumbnails/PG-23.jpg', ID: 442, albumID: 1021 },
        { src: 'PG-24.jpg', srct: 'thumbnails/PG-24.jpg', ID: 443, albumID: 1021 },
        { src: 'PG-25.jpg', srct: 'thumbnails/PG-25.jpg', ID: 444, albumID: 1021 },
      ]
    });
});